--Exercise 5: Triggers

CREATE TABLE Customers (
    CustomerID NUMBER PRIMARY KEY,
    Name VARCHAR2(100),
    DOB DATE,
    Balance NUMBER,
    LastModified DATE
);

CREATE TABLE Accounts (
    AccountID NUMBER PRIMARY KEY,
    CustomerID NUMBER,
    Balance NUMBER
);

CREATE TABLE Transactions (
    TransactionID NUMBER PRIMARY KEY,
    AccountID NUMBER,
    TransactionDate DATE,
    Amount NUMBER,
    TransactionType VARCHAR2(20)
);

CREATE TABLE AuditLog (
    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransactionID NUMBER,
    LogDate DATE,
    Action VARCHAR2(100)
);

INSERT INTO Customers
VALUES (
    1,
    'John Doe',
    TO_DATE('1985-05-15','YYYY-MM-DD'),
    10000,
    SYSDATE
);

INSERT INTO Customers
VALUES (
    2,
    'Jane Smith',
    TO_DATE('1990-07-20','YYYY-MM-DD'),
    15000,
    SYSDATE
);

COMMIT;

INSERT INTO Accounts
VALUES (
    1,
    1,
    5000
);

INSERT INTO Accounts
VALUES (
    2,
    2,
    3000
);

COMMIT;

INSERT INTO Transactions
VALUES (
    1,
    1,
    SYSDATE,
    500,
    'Deposit'
);

COMMIT;

INSERT INTO Transactions
VALUES (
    2,
    2,
    SYSDATE,
    1000,
    'Withdrawal'
);

COMMIT;

SELECT * FROM Customers;

SELECT * FROM Accounts;

SELECT * FROM Transactions;

SELECT * FROM AuditLog;


--Scenario 1: UpdateCustomerLastModified

CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
BEFORE UPDATE
ON Customers
FOR EACH ROW
BEGIN

    :NEW.LastModified := SYSDATE;

END;
/

UPDATE Customers
SET Balance = 15000
WHERE CustomerID = 1;

SELECT CustomerID,
       LastModified
FROM Customers;


--Scenario 2: LogTransaction

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT
ON Transactions
FOR EACH ROW
BEGIN

    INSERT INTO AuditLog(
        TransactionID,
        LogDate,
        Action
    )
    VALUES(
        :NEW.TransactionID,
        SYSDATE,
        'Transaction Inserted'
    );

END;
/

INSERT INTO Transactions
VALUES (
    1,
    1,
    SYSDATE,
    500,
    'Deposit'
);

SELECT * FROM AuditLog;

--Scenario 3: CheckTransactionRules

CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT
ON Transactions
FOR EACH ROW

DECLARE
    v_balance NUMBER;
BEGIN

    SELECT Balance
    INTO v_balance
    FROM Accounts
    WHERE AccountID = :NEW.AccountID;

    IF :NEW.TransactionType = 'Withdrawal'
       AND :NEW.Amount > v_balance THEN

        RAISE_APPLICATION_ERROR(
            -20001,
            'Insufficient Balance'
        );

    END IF;

    IF :NEW.TransactionType = 'Deposit'
       AND :NEW.Amount <= 0 THEN

        RAISE_APPLICATION_ERROR(
            -20002,
            'Deposit Amount Must Be Positive'
        );

    END IF;

END;
/

INSERT INTO Transactions
VALUES (
    2,
    1,
    SYSDATE,
    20000,
    'Withdrawal'
);

INSERT INTO Transactions
VALUES (
    3,
    1,
    SYSDATE,
    -100,
    'Deposit'
);